// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR2OSm-FxwAjzXgdpUvg6d1H-d-kGmpvo',
    appId: '1:590978230205:web:d15b3ea25a4cb1aec3d4d4',
    messagingSenderId: '590978230205',
    projectId: 'tokosegar-maserdine',
    authDomain: 'tokosegar-maserdine.firebaseapp.com',
    storageBucket: 'tokosegar-maserdine.firebasestorage.app',
    measurementId: 'G-23F5BW92VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUS7c7zpQ4NQUt4_g5S2Fn8_lwsLRFxFU',
    appId: '1:590978230205:android:f41832646dc4ba3fc3d4d4',
    messagingSenderId: '590978230205',
    projectId: 'tokosegar-maserdine',
    storageBucket: 'tokosegar-maserdine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRFz9L6K_j4PdunMmhQR-lscuQ1CUn8FM',
    appId: '1:590978230205:ios:e9dc295ddbc416bac3d4d4',
    messagingSenderId: '590978230205',
    projectId: 'tokosegar-maserdine',
    storageBucket: 'tokosegar-maserdine.firebasestorage.app',
    iosBundleId: 'com.example.tugas1Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRFz9L6K_j4PdunMmhQR-lscuQ1CUn8FM',
    appId: '1:590978230205:ios:e9dc295ddbc416bac3d4d4',
    messagingSenderId: '590978230205',
    projectId: 'tokosegar-maserdine',
    storageBucket: 'tokosegar-maserdine.firebasestorage.app',
    iosBundleId: 'com.example.tugas1Flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR2OSm-FxwAjzXgdpUvg6d1H-d-kGmpvo',
    appId: '1:590978230205:web:6f0837b28c7ea0dbc3d4d4',
    messagingSenderId: '590978230205',
    projectId: 'tokosegar-maserdine',
    authDomain: 'tokosegar-maserdine.firebaseapp.com',
    storageBucket: 'tokosegar-maserdine.firebasestorage.app',
    measurementId: 'G-SHCJ3PSW9K',
  );
}
